# -*- mode: python ; coding: utf-8 -*-
import os
import sys

# SPECPATH = directory of this spec file (packaging/)
# root     = project root (one level up)
root = os.path.dirname(SPECPATH)

# backend/ 를 sys.path 에 추가해야 collect_submodules('scripts') 가 동작한다.
sys.path.insert(0, os.path.join(root, 'backend'))

from PyInstaller.utils.hooks import collect_all, collect_submodules  # noqa: E402

# Detect AppName from .env
app_name = 'MyAgent'
env_path = os.path.join(root, '.env')
if os.path.exists(env_path):
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line.startswith('APP_NAME='):
                raw = line.split('=', 1)[1]
                # Strip inline comment (e.g. "MyAgent  # description")
                raw = raw.split('#', 1)[0]
                app_name = raw.strip().strip('"\'')
                break

# Generate backend/_version.py from pyproject.toml at build time.
# This file is gitignored; App.spec is the sole generator for frozen builds.
import tomllib as _tomllib
_pyproject_path = os.path.join(root, 'pyproject.toml')
with open(_pyproject_path, 'rb') as _f:
    _version = _tomllib.load(_f).get('project', {}).get('version', '0.0.0')
_version_py = os.path.join(root, 'backend', '_version.py')
with open(_version_py, 'w', encoding='utf-8', newline='\n') as _f:
    _f.write('# Auto-generated by App.spec — do not edit manually.\n')
    _f.write(f'__version__ = "{_version}"\n')
print(f'[spec] _version.py generated: {_version}')

# ---------------------------------------------------------------------------
# 번들용 .env 생성 — 업로드 전용 비밀(쓰기 자격증명)을 제외하고 빌드 채널을 주입한다.
# App.spec 이 .env 를 통째로 MEIPASS 에 넣으므로, 쓰기 권한이 있는 APP_REPO_USER/
# PASSWORD 가 모든 EXE 에 박혀 배포되면 탈취 시 저장소 전체가 노출된다. 런타임은
# 읽기 토큰(APP_REPO_READ_TOKEN)만 필요하므로 쓰기 자격증명을 제거한 사본을 번들한다.
# 빌드 채널은 release.ps1 -Channel 이 APP_BUILD_CHANNEL 환경변수로 주입한다(기본 prod).
# ---------------------------------------------------------------------------
_build_channel = os.environ.get('APP_BUILD_CHANNEL', 'prod').strip().lower()
_UPLOAD_ONLY_ENV_KEYS = {'APP_REPO_USER', 'APP_REPO_PASSWORD'}
_frozen_env_lines = []
_channel_written = False
if os.path.exists(env_path):
    with open(env_path, 'r', encoding='utf-8') as _f:
        for _line in _f:
            _stripped = _line.lstrip()
            if _stripped and not _stripped.startswith('#') and '=' in _stripped:
                _line_key = _stripped.split('=', 1)[0].strip()
                if _line_key in _UPLOAD_ONLY_ENV_KEYS:
                    continue  # 쓰기 자격증명은 EXE 에 번들하지 않는다
                if _line_key == 'APP_BUILD_CHANNEL':
                    _frozen_env_lines.append(f'APP_BUILD_CHANNEL={_build_channel}\n')
                    _channel_written = True
                    continue
            if not _line.endswith('\n'):
                _line += '\n'
            _frozen_env_lines.append(_line)
if not _channel_written:
    _frozen_env_lines.append(f'APP_BUILD_CHANNEL={_build_channel}\n')

_frozen_env_path = os.path.join(root, 'build', '.env')
os.makedirs(os.path.join(root, 'build'), exist_ok=True)
with open(_frozen_env_path, 'w', encoding='utf-8', newline='') as _f:
    _f.writelines(_frozen_env_lines)
print(f'[spec] frozen .env generated (channel={_build_channel}, upload secrets stripped)')

# ---------------------------------------------------------------------------
# backend/scripts/ — 사내 스크립트 패키지.
# backend/ 가 pathex 에 있으므로 collect_submodules 로 전체 서브모듈을 수집한다.
# scripts/ 에 새 .py 파일을 추가해도 spec 을 수정할 필요가 없다.
# ---------------------------------------------------------------------------
scripts_hidden = collect_submodules('scripts')

# ---------------------------------------------------------------------------
# APP_ALLOWED_LIBRARIES — .env 에서 읽어 외부 라이브러리를 hiddenimports 에 추가.
# resolver.py 가 importlib.import_module(string) 을 사용하므로
# PyInstaller 정적 분석에서 누락되는 라이브러리를 여기서 강제 수집한다.
# ---------------------------------------------------------------------------
_allowed_libs_raw = ''
if os.path.exists(os.path.join(root, '.env')):
    with open(os.path.join(root, '.env'), 'r', encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line.startswith('APP_ALLOWED_LIBRARIES='):
                _allowed_libs_raw = _line.split('=', 1)[1].split('#', 1)[0].strip()
                break

_allowed_extra_datas = []
_allowed_extra_binaries = []
_allowed_extra_hidden = []
for _lib in [l.strip() for l in _allowed_libs_raw.split(',') if l.strip()]:
    if _lib == 'scripts':
        continue  # scripts 는 위에서 별도 처리
    try:
        _d, _b, _h = collect_all(_lib)
        _allowed_extra_datas += _d
        _allowed_extra_binaries += _b
        _allowed_extra_hidden += _h
        print(f'[spec] collect_all({_lib!r}): {len(_h)} hidden imports')
    except Exception as _e:
        print(f'[spec] collect_all({_lib!r}) 실패 — hiddenimports 에 루트만 추가: {_e}')
        _allowed_extra_hidden.append(_lib)

# ---------------------------------------------------------------------------
# extensions/ — 확장 툴(별도 SPA + API). 런타임에 필요한 backend/ 와 frontend/dist 만
# 선별 번들한다 (node_modules·src·tests 제외 → EXE 비대화 방지).
# core.extensions_loader 가 런타임에 MEIPASS/extensions 를 스캔해 파일 경로로 적재하므로
# collect_submodules/hiddenimports 가 불필요하다. 폴더가 없거나 비면 빈 리스트 → no-op.
# 확장 1개 폴더를 지워도 spec 수정 없이 다음 빌드에 자동 반영(삭제 = 미수집).
# ---------------------------------------------------------------------------
import glob as _glob
# dev 전용 확장 — frozen/prod EXE 에 번들하지 않는다. tracer 는 디버그 트레이스 뷰어로,
# 트레이스 자체가 dev(APP_DEBUG_TRACE)에서만 생성되므로 운영 빌드에서 제외한다.
# 로컬에 stale 한 dist 가 남아 있어도 여기서 걸러 운영 EXE 에 새지 않게 한다.
_DEV_ONLY_EXTENSIONS = {'tracer'}
_extension_datas = []
for _ext in _glob.glob(os.path.join(root, 'extensions', '*')):
    if not os.path.isdir(_ext):
        continue
    _name = os.path.basename(_ext)
    if _name in _DEV_ONLY_EXTENSIONS:
        print(f'[spec] extension skipped (dev-only): extensions/{_name}')
        continue
    _backend = os.path.join(_ext, 'backend')
    _dist = os.path.join(_ext, 'frontend', 'dist')
    _manifest = os.path.join(_ext, 'extension.json')
    if os.path.isdir(_backend):
        _extension_datas.append((_backend, f'extensions/{_name}/backend'))
        print(f'[spec] extension bundled: extensions/{_name}/backend')
    if os.path.isdir(_dist):
        _extension_datas.append((_dist, f'extensions/{_name}/frontend/dist'))
        print(f'[spec] extension bundled: extensions/{_name}/frontend/dist')
    # 선택적 메타데이터 매니페스트 — list_available_extensions() 가 런처 드롭다운에 쓴다.
    if os.path.isfile(_manifest):
        _extension_datas.append((_manifest, f'extensions/{_name}'))
        print(f'[spec] extension bundled: extensions/{_name}/extension.json')

a = Analysis(
    [os.path.join(root, 'backend', 'main.py')],
    pathex=[os.path.join(root, 'backend')],
    binaries=[] + _allowed_extra_binaries,
    datas=[
        # source -> destination inside sys._MEIPASS
        # 원본 .env 가 아니라 위에서 생성한 필터링·채널주입본을 번들한다(쓰기 자격증명 제외).
        (_frozen_env_path, '.'),
        (os.path.join(root, 'build', 'web'), 'web'),
        (os.path.join(root, 'build', 'updater', 'Updater.exe'), 'updater'),
        # Agent guideline directories — backend/agent/registries/{prompts,skills}.py 가 MEIPASS 에서 읽음.
        (os.path.join(root, 'PROMPTS'), 'PROMPTS'),
        (os.path.join(root, 'SKILLS'), 'SKILLS'),
        (os.path.join(root, 'AGENTS'), 'AGENTS'),
    ] + _allowed_extra_datas + _extension_datas,
    hiddenimports=[
        '_version',
        'core',
        'core.config',
        'core.browser',
        'core.updater',
        'core.version',
        'core.server_socket',
        'agent',
        'agent.config',
        'agent.harness',
        'agent.harness.loop',
        'agent.harness.budget',
        'agent.harness.tool_exec',
        'agent.harness.dispatch',
        'agent.harness.dispatch.sequential',
        'agent.harness.dispatch.parallel',
        'agent.harness.dispatch.spec_filter',
        'agent.harness.dispatch.result_format',
        'agent.harness.state',
        'agent.harness.state.todo',
        'agent.harness.state.balancing',
        'agent.harness.state.loop_guard',
        'agent.harness.prompt',
        'agent.harness.prompt.compose',
        'agent.harness.prompt.sections',
        'agent.harness.prompt.artifacts',
        'agent.harness.prompt.api_refs',
        'agent.harness.prompt.wind_down',
        'agent.guard',
        'agent.models',
        'agent.stores.conversation',
        'agent.stores.agent_state',
        'agent.registries.prompts',
        'agent.registries.skills',
        'agent.registries.tools',
        'agent.registries.agents',
        'agent.providers.factory',
        'agent.providers.mock',
        'agent.providers.openai',
        'settings.config',
        'settings.models',
        'settings.store',
        'settings.masking',
        'api',
        'api.deps',
        'api.chat',
        'api.presence',
        'api.update',
        'api.settings',
        'api.skills',
        # runtime 인프라 — importlib.import_module 동적 호출로 정적 분석 누락 방지
        'agent.runtime',
        'agent.runtime.resolver',
        'agent.runtime.namespace',
        'agent.runtime.serialization',
        'agent.runtime.evaluator',
        'agent.runtime.introspect',
        'agent.tools.runtime',
    ] + scripts_hidden + _allowed_extra_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=app_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
